### ISSUE TITLE
Wrong event handling

### ISSUE THREAD

**Issue by int-0** [tipam/pi3d#210]
Hi,
I've written a simple loop to test EventHandler(). I check a keyboard handler and a mouse handler. Everything looks fine, but when I move the mouse I get the following error:
```
Traceback (most recent call last):
  File "../src/__init__.py", line 62, in update
    self.inputs.do_input_events()
  File "build/bdist.linux-x86_64/egg/pi3d/event/Event.py", line 103, in do_input_events
    if self.handler.event(event) and self.unhandledHandler:
  File "build/bdist.linux-x86_64/egg/pi3d/event/EventHandler.py", line 94, in event
    self.rely[event.stream.deviceIndex] += event.eventValue
IndexError: list index out of range
```
After some investigation, I get the wrong deviceIndex value, this value is 10 and self.rely is a 4-element list. And also I print the event information that causes this issue. The event is:
`DEBUG:pi3d.event.EventHandler:Input event keyboard[10], 1 -- 1492019728.066793: 0x2(0x1) = 0x2`

As you can see, this event is "keyboard" but is not true, this event is emited when I move the mouse.
I can try to fix by myself but is very hard for me without more documentation, sorry...

I have more than one mouse (a Wacom tablet with 3 pointing devices). I can send you a dump of my _/proc/bus/input/devices_ file if you want.

Could you help me? can I help you?

Thank you!

**Comment by paddywwoof** [comment]
Sounds like this does need sorting out. I'm away at the moment and won't get back till Saturday night but will have a look when I get home.

I have found that I run into variable behaviour when running pi3d on different laptops which allocate different pointing devices. I don't know if it's possible to make this automatically fixable but it is necessary to have a clearer explanation of what's going on so people can tweak the setup more easily. (The event system was devised by Rurwin and is rather sophisticated (i.e. I've never really got the bottom of how it all works!))

**Comment by paddywwoof** [comment]
@int-0, Hmm now I look at it again, the event system is certainly complicated! Maybe if you give me a copy of your simple loop I will try and reproduce the error. And, yes, /proc/bus/input/devices would be useful too as that looks to be where find_devices() generates deviceIndex

**Comment by int-0** [comment]
Hi,
First of all... thank you!

Ok, I get a following error when I move the mouse (not the tablet!):
```Traceback (most recent call last):
  File "test_inputs.py", line 20, in <module>
    inputs.do_input_events()
  File "build/bdist.linux-x86_64/egg/pi3d/event/Event.py", line 103, in do_input_events
    if self.handler.event(event) and self.unhandledHandler:
  File "build/bdist.linux-x86_64/egg/pi3d/event/EventHandler.py", line 88, in event
    self.relx[event.stream.deviceIndex] += event.eventValue
IndexError: list index out of range
```
And the code is:
```python
#!/usr/bin/env python
#

import traceback
import pi3d

def keyboard_handler(sourceType, sourceIndex, key, value):
    print sourceType, sourceIndex, key, value

def mouse_handler(sourceType, sourceIndex, x, y, v, h):
    print sourceType, sourceIndex, x, y, v, h


display = pi3d.Display.create(w=1024, h=768, frames_per_second=20.0)
inputs = pi3d.event.Event.InputEvents(keyboard_handler, mouse_handler)

cycles = 100
while (display.loop_running()) and (cycles > 0):
    try:
        inputs.do_input_events()
    except Exception, e:
        traceback.print_exc()
    finally:
        cycles -= 1
```

And also, my _/proc/bus/input/devices_ file:
```I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input3
U: Uniq=
H: Handlers=kbd event0 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:03/LNXVIDEO:01/input/input5
U: Uniq=
H: Handlers=kbd event2 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0010 Vendor=001f Product=0001 Version=0100
N: Name="PC Speaker"
P: Phys=isa0061/input0
S: Sysfs=/devices/platform/pcspkr/input/input6
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=40001
B: SND=6

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA ATI HDMI HDMI/DP,pcm=3"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:02.1/0000:01:00.1/sound/card1/input7
U: Uniq=
H: Handlers=event4 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA ATI HDMI HDMI/DP,pcm=7"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:02.1/0000:01:00.1/sound/card1/input8
U: Uniq=
H: Handlers=event5 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA ATI HDMI HDMI/DP,pcm=8"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:02.1/0000:01:00.1/sound/card1/input9
U: Uniq=
H: Handlers=event6 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA ATI HDMI HDMI/DP,pcm=9"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:02.1/0000:01:00.1/sound/card1/input10
U: Uniq=
H: Handlers=event7 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA ATI HDMI HDMI/DP,pcm=10"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:02.1/0000:01:00.1/sound/card1/input11
U: Uniq=
H: Handlers=event8 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Front Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input12
U: Uniq=
H: Handlers=event9 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Rear Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input13
U: Uniq=
H: Handlers=event10 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Line"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input14
U: Uniq=
H: Handlers=event11 
B: PROP=0
B: EV=21
B: SW=2000

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Line Out Front"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input15
U: Uniq=
H: Handlers=event12 
B: PROP=0
B: EV=21
B: SW=40

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Line Out Surround"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input16
U: Uniq=
H: Handlers=event13 
B: PROP=0
B: EV=21
B: SW=40

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Line Out CLFE"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input17
U: Uniq=
H: Handlers=event14 
B: PROP=0
B: EV=21
B: SW=40

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Line Out Side"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input18
U: Uniq=
H: Handlers=event15 
B: PROP=0
B: EV=21
B: SW=40

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HD-Audio Generic Front Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:14.2/sound/card0/input19
U: Uniq=
H: Handlers=event16 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Eee PC WMI hotkeys"
P: Phys=eeepc-wmi/input0
S: Sysfs=/devices/platform/eeepc-wmi/input/input20
U: Uniq=
H: Handlers=kbd rfkill event17 
B: PROP=0
B: EV=100013
B: KEY=7e40000 0 800000000000 0 0 1400b00100000 300180001100800 e000000000000 2
B: MSC=10

I: Bus=0003 Vendor=054c Product=0155 Version=0100
N: Name="ov519"
P: Phys=usb-0000:00:12.0-2/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.0/usb8/8-2/input/input21
U: Uniq=
H: Handlers=kbd event18 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0003 Vendor=045e Product=0745 Version=0111
N: Name="Microsoft Microsoft® 2.4GHz Transceiver v7.0"
P: Phys=usb-0000:00:12.2-1.1/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.1/1-1.1:1.0/0003:045E:0745.0010/input/input48
U: Uniq=
H: Handlers=sysrq kbd leds event19 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff800000000007ff febeffdff3cfffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=045e Product=0745 Version=0111
N: Name="Microsoft Microsoft® 2.4GHz Transceiver v7.0"
P: Phys=usb-0000:00:12.2-1.1/input1
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.1/1-1.1:1.1/0003:045E:0745.0011/input/input49
U: Uniq=
H: Handlers=kbd mouse0 event20 
B: PROP=0
B: EV=1f
B: KEY=3f0003007f 0 0 483ffff17aff32d bf54444600000000 1f0001 130f938b17c000 677bfad9415fed 9ed68000004400 10000002
B: REL=3c3
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=045e Product=0745 Version=0111
N: Name="Microsoft Microsoft® 2.4GHz Transceiver v7.0"
P: Phys=usb-0000:00:12.2-1.1/input2
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.1/1-1.1:1.2/0003:045E:0745.0012/input/input50
U: Uniq=
H: Handlers=sysrq kbd event21 
B: PROP=0
B: EV=10001f
B: KEY=3f0003007f 0 0 4c3ffff17aff32d bf54445600000000 1 130f938b17c007 ffff7bfad951dfff febeffdfffefffff fffffffffffffffe
B: REL=40
B: ABS=10100000000
B: MSC=10

I: Bus=0003 Vendor=25a7 Product=2433 Version=0101
N: Name="2.4G 2.4G Wireless Device"
P: Phys=usb-0000:00:12.2-1.2/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.2/1-1.2:1.0/0003:25A7:2433.0013/input/input51
U: Uniq=
H: Handlers=sysrq kbd leds event22 
B: PROP=0
B: EV=120013
B: KEY=e080ffdf01cfffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0003 Vendor=25a7 Product=2433 Version=0101
N: Name="2.4G 2.4G Wireless Device"
P: Phys=usb-0000:00:12.2-1.2/input1
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.2/1-1.2:1.1/0003:25A7:2433.0014/input/input52
U: Uniq=
H: Handlers=kbd mouse1 event23 
B: PROP=0
B: EV=1f
B: KEY=3f0003007f 0 0 483ffff17aff32d bf54444600000000 1f0001 130f938b17c000 677bfad941dfed 9ed68000004400 10000002
B: REL=1c3
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=056a Product=0028 Version=0110
N: Name="Wacom Intuos5 touch L Pen"
P: Phys=usb-0000:00:12.2-1.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.3/1-1.3:1.0/0003:056A:0028.0015/input/input53
U: Uniq=
H: Handlers=mouse2 event24 
B: PROP=1
B: EV=1f
B: KEY=1cdf 1f0000 0 0 0 0
B: REL=100
B: ABS=1000f000167
B: MSC=1

I: Bus=0003 Vendor=056a Product=0028 Version=0110
N: Name="Wacom Intuos5 touch L Pad"
P: Phys=usb-0000:00:12.2-1.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.3/1-1.3:1.0/0003:056A:0028.0015/input/input55
U: Uniq=
H: Handlers=event25 js0 
B: PROP=0
B: EV=b
B: KEY=800 1ff 0 0 0 0
B: ABS=10000000103

I: Bus=0003 Vendor=056a Product=0028 Version=0110
N: Name="Wacom Intuos5 touch L Finger"
P: Phys=usb-0000:00:12.2-1.3/input1
S: Sysfs=/devices/pci0000:00/0000:00:12.2/usb1/1-1/1-1.3/1-1.3:1.1/0003:056A:0028.0016/input/input57
U: Uniq=
H: Handlers=mouse3 event26 
B: PROP=1
B: EV=b
B: KEY=e520 0 0 0 0 0
B: ABS=263800000000003

```
You can send me code snippets or anything you need to run in my system... thank you again!

**Comment by paddywwoof** [comment]
Hi, thanks for that. The event.FindDevices.find_devices() function looks to go through the input/devices file and generate a list depending on 'kbd' 'mouse' or 'js' occurring in the line beginning 'H' which means that on your system it should get up to a total of 11 keyboards, 4 mice and 1 joystick. A lot of mice seem to also call themselves keyboards - presumably they have some keyboard functionality built into them.

Anyway, I managed to reproduce your error after a fashion by plugging more and more mice and graphics tablets into my laptop. The problems seemed to be solved by increasing the list sizes in EventHandler.py

I have pushed a modified version to github develop branch. You can try it out by cloning from github, checkout develop then adding

```
import sys
sys.path.insert(1, '/home/int0/pi3d') #or whereever
import pi3d
```

**Comment by int-0** [comment]
yeah, you rocks!

Now it works... anyway I'm reading some code in [python-evdev](https://github.com/gvalkov/python-evdev) and it seems that this _magic_ number can be detected. But for me (at the moment) is out of scope... if you are agree this issue could be closed... :)

**Comment by int-0** [comment]
Hahaha... mouse events are reported as "keyboard" instead of "mouse"... but is fine for me,

Thank you again! ;)

**Comment by paddywwoof** [comment]
Yes, I've not tried to figure out how the pi3d.event system differentiates kbd mouse js where they're all on the same device. As you say it probably doesn't matter! As you're happy I will close the issue. (and move the master branch to v2.19)
