### ISSUE TITLE
AttributeError: 'DisplayOpenGL' object has no attribute 'context'

### ISSUE THREAD

**Issue by cnichte** [tipam/pi3d#260]
I have setup pic frame on a fresh raspberry pi4, with an Display on the HDMI Port:

- PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
- NAME="Raspbian GNU/Linux"
- VERSION_ID="11"
- VERSION="11 (bullseye)"
- VERSION_CODENAME=bullseye
- ID=raspbian
- ID_LIKE=debian

First launch from the Terminal gets me the following Errors:

```
picframe
INFO:start.py:starting ['/usr/local/bin/picframe']
INFO:model.Model:Open config file: /home/pi/picframe_data/config/configuration.yaml:
Traceback (most recent call last):
  File "/usr/local/bin/picframe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/picframe/start.py", line 136, in main
    c.start()
  File "/usr/local/lib/python3.9/dist-packages/picframe/controller.py", line 326, in start
    self.__viewer.slideshow_start()
  File "/usr/local/lib/python3.9/dist-packages/picframe/viewer_display.py", line 426, in slideshow_start
    self.__display = pi3d.Display.create(x=self.__display_x, y=self.__display_y,
  File "/usr/local/lib/python3.9/dist-packages/pi3d/Display.py", line 569, in create
    display.opengl.create_display(x, y, w, h, depth=depth, samples=samples, layer=layer,
  File "/usr/local/lib/python3.9/dist-packages/pi3d/util/DisplayOpenGL.py", line 120, in create_display
    assert self.context != EGL_NO_CONTEXT and self.context is not None
AttributeError: 'DisplayOpenGL' object has no attribute 'context'
```

What's going wrong here?

best regards

**Comment by cnichte** [comment]
Woran place :-)
